package DataGenerationAPI;



public class DataGenerationClass {
	
	public static String autoGeneratedEmail() {
		String firstPart = "randomemail";
		String domain = "@gmail.com";
		int randomNumber = (int) (Math.random() * 100);
		
		String email = firstPart + randomNumber + domain;
		return email;
	}
	


}
