@Regression
Feature: End to End Account Creation

  Background: Setup API Test
    * def tokenGeneration = callonce read('GenerateTokenTest.feature')
    * def token = tokenGeneration.response.token
    Given url "https://tek-insurance-api.azurewebsites.net"
    * def dataGeneration = Java.type('DataGenerationAPI.DataGenerationClass')
    * def autoEmail = dataGeneration.autoGeneratedEmail()

  Scenario: End to End Adding Account Test
    #Create Account
    Given path "/api/accounts/add-primary-account"
    And header Authorization = "Bearer " + token
    And request
      """
      {
      "email": "#(autoEmail)",
      "firstName": "Elon",
      "lastName": "Mask",
      "title": "Mr.",
      "gender": "MALE",
      "maritalStatus": "MARRIED",
      "employmentStatus": "SPACEX CEO",
      "dateOfBirth": "1975-07-03T00:55:07.369Z",
      }
      """
    When method post
    Then status 201
    And print response
    And assert response.email == autoEmail
    * def primaryId = response.id
    #Add Address
    Given path "/api/accounts/add-account-address"
    And header Authorization = "Bearer " + token
    And param primaryPersonId = primaryId
    And request
      """
      {
        "addressType": "Home",
      "addressLine1": "0909 Elon Str",
      "city": "LA",
      "state": "CA",
      "postalCode": "34509",
      "countryCode": "001",
      "current": true
      }
      """
    When method post
    Then status 201
    And print response
    And assert response.addressLine1 == "0909 Elon Str"
    #Add Phone
    Given path "/api/accounts/add-account-phone"
    And header Authorization = "Bearer " + token
    And param primaryPersonId = primaryId
    And request
      """
      {
       "phoneNumber": "9160909522",
      "phoneExtension": "003",
      "phoneTime": "Any Time",
      "phoneType": "Mobile"
      }
      """
    When method post
    Then status 201
    And print response
    And assert response.phoneNumber == "9160909522"
    #Add Car
    Given path "/api/accounts/add-account-car"
    And header Authorization = "Bearer " + token
    And param primaryPersonId = primaryId
    And request
      """
      {
      "make": "Tesla",
      "model": "X",
      "year": "2024",
      "licensePlate": "Tesla12340Elon"
      }
      """
    When method post
    Then status 201
    And assert response.licensePlate == "Tesla12340Elon"
    #Get Account
    Given path "/api/accounts/get-account"
    And header Authorization = "Bearer " + token
    And param primaryPersonId = primaryId
    When method get
    Then status 200
    And print response
    And assert response.primaryPerson.id == primaryId
    And print primaryId
